admin_password: admin
rancher_version: v2.6.0
ROS_version: 1.5.1
# Empty defaults to latest non-experimental available
k8s_version: "v1.20.10-rancher1-1"
server:
  cpus: 1
  memory: 1500
node:
  count: 1
  cpus: 2
  memory: 2400
ip:
  master: 192.168.56.100
  server: 192.168.56.101
  node:   192.168.56.111
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: private_network
