admin_password: adminPassword
rancher_version: v2.6.8
ROS_version: 1.5.1
# Empty defaults to latest non-experimental available
k8s_version: "v1.22.9-rancher1-1"
server:
  cpus: 2
  memory: 4000
node:
  count: 1
  cpus: 1
  memory: 1500
  open-iscsi: disabled
ip:
  master: 192.168.56.100
  server: 192.168.56.101
  node:   192.168.56.111
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: private_network
